use_default_settings: true

general:
  instance_name: 'searxng'

search:
  autocomplete: 'google'
  formats:
    - html
    - json

server:
  limiter: false

engines:
  - name: wolframalpha
    disabled: false
